### PR TITLE
Travis automatic git create Release and npm update package

### PR DESCRIPTION
**Pull request by poratuk**
Added dist folder to the .gitignore. Removed it from git.

All process publishing look like:
* Developer forks or branches
* Developer add feature / solves issue
* Developer send a pull request
* Travis runs the tests on the pull request
* I review the pull request
* I accept and merge the pull request
* I create  new version tag like "vX.X.X....."
* Travis:
  - runs the tests
  - builds the dist files
  - zips the dist folder 
  - deploys as GitHub release
  - deploys to npm

### CODE REVIEW

**Comment by jasny** [comment]
Changes in the JavaScript files seem to have nothing to do with Travis and unnecessary: 

* application.js
* customizer.js
* js/*

Please revert them using `git checkout master application.js customer.js js`

It some changes are needed, please apply only those changes without changing the formatting.

**Comment by poratuk** [comment]
Changes need for success grunt test. 
Without success grunt test trevis do not runs deploy.

**Comment by poratuk** [comment]
But wait, I maybe have some errors there with returns. I will push new versions.

**Comment by poratuk** [comment]
Removed conflicts

**Pull request merged**
