### PR TITLE
trigger clear.bs.fileinput event if user cancels

### PR DESCRIPTION
**Pull request by Dehalion**
this.clear() expects the event object as parameter if it is triggered by the user
otherwise it won't trigger the 'clear.bs.fileinput' event

### CODE REVIEW

**Comment by Dehalion** [comment]
sorry, that was premature.
will fix it and create a new pull request

**Comment by jasny** [comment]
@Dehalion You can just fix it and push to your 'master' branch. The pull request will automatically update.

That's said. It's better not to do a pull request from the master branch, but to create a specific branch for the pull request instead.

**Comment by Dehalion** [comment]
@jasny I see. Thanks for the info. Thought I wouldn't need a separate branch for this because it's just one letter. Should've known better :(

Now I trigger the `clear.bs.fileinput` event manually because giving a parameter to `this.clear()` triggers an endless loop (because it also triggers change again)

**Comment by Dehalion** [comment]
The Travic CI build failed, but this is not due to my change I think:

```
>> Local Npm module "grunt-contrib-qunit" not found. Is it installed?
Warning: Task "qunit" not found. Use --force to continue.
```

**Pull request merged**
